billboard/billboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
urlpatterns = [
    path('admin/', admin.site.urls), # Comment this out to add User model
    path('accounts/', include("django.contrib.auth.urls")),
    path('rankings/', include("rankings.urls")),
    path('core/', include('core.urls')),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    
]

billboard/core/urls.py
from django.urls import path
from .views import RegisterView

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
]

billboard/rankings/urls.py
from django.urls import path
from . import views

app_name = 'rankings'

urlpatterns = [
    path("songs/", views.song_list, name="song_list"),
    path("songs/<int:pk>/", views.SongDetailView.as_view(), name="song_detail"),
    path('search/', views.SearchView.as_view(), name='search'),
    path('songs/<int:song_id>/toggle_favorites/', views.toggle_favorites, name='toggle_favorites'),
    path('update-songs/', views.update_songs, name='update_songs'),
    path('favorites/', views.FavoriteListView.as_view(), name='favorites'),
    path('data-analysis/', views.data_analysis, name='data_analysis'),
    path('artists/', views.ArtistView.as_view(), name='artists')
    ]

billboard/core/models.py
from django.db import models

# Create your models here.

billboard/core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

billboard/core/views.py
from django.shortcuts import render

# Create your views here.

from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .forms import CustomUserCreationForm

class RegisterView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')

billboard/core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  {% block head %}
	{% endblock %}
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/static.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <div class="col text-center">
            <h1 class="header"><a href="/">TOP 100 BILLBOARD</a></h1>
        </div>
        <ul class="list flex-row">
            {% url 'rankings:song_list' as url1 %}
            {% url 'rankings:search' as url2 %}
            {% url 'rankings:favorites' as url3 %}
            {% url 'rankings:data_analysis' as url4 %}
            {% url 'rankings:artists' as url5 %}
            <li class="item"> <a href="{{url1}}" {% if request.path == url1 %} class="active"{% endif %}> Songs </a> </li>
            <li class="item"> <a href="{{url2}}" {% if request.path == url2 %} class="active"{% endif %}> Search </a> </li>
            <li class="item"> <a href="{{url5}}" {% if request.path == url5 %} class="active"{% endif %}> Artists </a> </li>
            <li class="item"> <a href="{{url3}}" {% if request.path == url3 %} class="active"{% endif %}> Favorites </a> </li>
            <li class="item"> <a href="{{url4}}" {% if request.path == url4 %} class="active"{% endif %}> Data Analysis </a> </li>
        </ul>
    </div>
  </nav>
  <main>
    {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
    {% endif %}
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </main>
</body>
  {% block js %}
  {% endblock js %}
</html>

billboard/core/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}

{% if user.is_authenticated %}
Hi {{ user.username }}!
<form action="{% url 'logout' %}" method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-secondary">Log Out</button>
</form>
{% else %}

<p>You are not logged in!</p>
<a href="{% url 'login' %}" class="btn btn-primary">Log In</a><br>
<a href="{% url 'register' %}" class="btn btn-secondary">Register</a>
{% endif %}
{% endblock %}