billboard/billboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
urlpatterns = [
    path('admin/', admin.site.urls), # Comment this out to add User model
    path('accounts/', include("django.contrib.auth.urls")),
    path('rankings/', include("rankings.urls")),
    path('core/', include('core.urls')),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    
]

billboard/core/urls.py
from django.urls import path
from .views import RegisterView

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
]

billboard/rankings/urls.py
from django.urls import path
from . import views

app_name = 'rankings'

urlpatterns = [
    path("songs/", views.song_list, name="song_list"),
    path("songs/<int:pk>/", views.SongDetailView.as_view(), name="song_detail"),
    path('search/', views.SearchView.as_view(), name='search'),
    path('songs/<int:song_id>/toggle_favorites/', views.toggle_favorites, name='toggle_favorites'),
    path('update-songs/', views.update_songs, name='update_songs'),
    path('favorites/', views.FavoriteListView.as_view(), name='favorites'),
    path('data-analysis/', views.data_analysis, name='data_analysis'),
    path('artists/', views.ArtistView.as_view(), name='artists')
    ]

billboard/rankings/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    email = models.EmailField(unique=True, blank=False)

class Song(models.Model):
    title = models.CharField(max_length=255)
    artist = models.CharField(max_length=255)
    rank = models.IntegerField()
    chart_date = models.DateField()
    album_name = models.CharField(max_length=255, blank=True, null=True)
    peak_position = models.IntegerField(blank=True, null=True)
    weeks_on_chart = models.IntegerField(blank=True, null=None)
    label = models.CharField(max_length=255, blank=True, null=True)
    genre = models.CharField(max_length=255, blank=True, null=True)
    weeks_at_no_1 = models.IntegerField(blank=True, null=True)
    last_week = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.title} by {self.artist}"

class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    added_date = models.DateField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'song')
        
    def __str__(self):
        return f"{self.user.username} - {self.song.title}"

billboard/rankings/views.py
from django.urls import reverse_lazy
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from .models import Song, Favorite, User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms.models import model_to_dict
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.utils.dateparse import parse_date
from django.urls import reverse
import subprocess
from django.http import JsonResponse, HttpResponseNotAllowed, HttpResponse
from .initialize2 import update
from .initialize1 import process_song_data



@login_required
def song_list(request):
    date_str = request.GET.get('date')
    if date_str:
        date = parse_date(date_str)
        songs = Song.objects.filter(chart_date=date).order_by('rank')
    else:
        date = parse_date('2024-06-05')
        songs = Song.objects.filter(chart_date=date).order_by('rank')

    return render(request, 'rankings/song_list.html', {'songs': songs})

@login_required
def update_songs(request):
    date_str = request.GET.get('date')
    action = request.GET.get('action')

    redirect_url = reverse('rankings:song_list')
    if date_str:
        redirect_url += f"?date={date_str}"

    if action == 'filter':
        return redirect(redirect_url)
    elif action == 'fetch' and date_str:
        try:
            process_song_data(date_str)
        except Exception as e:
            messages.error(request, f'Error updating songs data: {str(e)}')
    else:
        messages.error(request, "Please select a valid date to fetch data.")
    
    return redirect(redirect_url)

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from io import BytesIO
import base64
class SongDetailView(LoginRequiredMixin, DetailView):
    model = Song
    template_name = 'rankings/song_detail.html'
    context_object_name = 'song'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        update()
        favorite = Favorite.objects.filter(user=self.request.user, song__title=self.object.title)
        if favorite.exists():
            is_favorite = 1
        else:
            is_favorite = 0
        song_dict = {
            'id': self.object.id,
            'title': self.object.title,
            'artist': self.object.artist,
            'album_name': self.object.album_name,
            'label': self.object.label,
            'favorite': is_favorite,
        }
        context['song_dict'] = song_dict
        
        song_entries = Song.objects.filter(title=self.object.title, artist=self.object.artist).order_by('chart_date')
        dates = [song.chart_date for song in song_entries]
        ranks = [song.rank for song in song_entries]
        
        plt.figure(figsize=(10, 5))
        plt.plot(dates, ranks)
        plt.gca().invert_yaxis()
        plt.title(f"Billboard History for {self.object.title}")
        plt.xlabel('Date')
        plt.ylabel('Billboard Rank')
        plt.grid(True)
        plt.xticks(rotation=45)
        
        buf = BytesIO()
        plt.savefig(buf, format='png', bbox_inches='tight')
        plt.close()
        buf.seek(0)
        image_base64 = base64.b64encode(buf.getvalue()).decode('utf-8')
        context['chart_image'] = image_base64
        
        return context


@login_required
def toggle_favorites(request, song_id):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'], 'Invalid method')

    song = get_object_or_404(Song, pk=song_id)
    favorite = Favorite.objects.filter(user=request.user, song__title=song.title)
    redirect_to_favorites = request.POST.get('redirect_to_favorites', False)
    
    if favorite.exists():
        favorite.delete()
        if redirect_to_favorites:
            return redirect('rankings:favorites')
        return JsonResponse({'status': 'removed'})
    else:
        Favorite.objects.create(user=request.user, song=song)
        return JsonResponse({'status': 'added'})

class SearchView(LoginRequiredMixin, ListView):
    model = Song
    template_name = 'rankings/search.html'
    context_object_name = 'songs'

    def get_queryset(self):
        query = self.request.GET.get('q', '')
        if query:
            return Song.objects.filter(title__icontains=query).distinct('title')
        return Song.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q', '')
        return context

class FavoriteListView(LoginRequiredMixin, ListView):
    model = Favorite
    template_name = 'rankings/favorites.html'

    def get_queryset(self):
        return Favorite.objects.filter(user=self.request.user).order_by('added_date')

class ArtistView(LoginRequiredMixin, ListView):
    model = Song
    template_name = 'rankings/artists.html'
    context_object_name = 'songs'

    def get_queryset(self):
        char = self.request.GET.get('c', '')
        if char: 
            return Song.objects.filter(artist__icontains=char).distinct('title')
        else:
            return Song.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['char'] = self.request.GET.get('c', '')
        return context

@login_required
def data_analysis(request):
    return render(request, 'rankings/data_analysis.html')

billboard/rankings/templates/rankings/artists.html
{% extends "base.html" %}

{% block content %}
<h2>Search by Artist Name</h2>
<p>Filter songs based on an artist </p>

<form method="get" action="{% url 'rankings:artists' %}">
    <input type="text" name="c" value="{{ char }}" placeholder="Search for an artist">
    <button type="submit">Search</button>
</form>

{% if songs %}
    <ul>
        {% for song in songs %}
        <li><a href="{% url 'rankings:song_detail' song.id %}">{{ song.title }}</a> by <b>{{ song.artist }}</b></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No artist found.</p>
{% endif %}


{% endblock %}

billboard/rankings/templates/rankings/data_analysis.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>Data Analysis for Past 30 Weeks</h1>
    <h3>(Fridays: November 17, 2023 to June 7th, 2024)</h3>
    <img src="/static/images/weeks_distribution.png"></img>
    <p>Here, we can see that most songs stay less than 10 weeks
        on the billboard, with over 100 songs. After that, there
        is an even distribution of around 30 songs for each cluster
        until just under 40 weeks. Then, there is another distribution
        of around 10 songs until just under 65 weeks.
    </p>
    <img src="/static/images/peaks.png"></img>
    <p>Most songs' peak position is at number 1. Then, it seems to descend
        in numerical order, but peaks of 5 to 10 don't seem to have any 
        correlation for the frequency of those peak positions.
    </p>
    <img src="/static/images/labels.png"></img>
    <p>Most explicit songs don't stay on the billboard for much time, with
        most having a tenure of under 10 weeks. However, the non-explicit 
        songs have a more even distribution, with most songs having a tenure 
        of greater than 20 weeks on the chart. This indicates that non-explicit
        songs experience greater success.
    </p>
    <img src="/static/images/rank_changes.png"></img>
    <p>This ranking is just a bit of interesting data for the change in rankings
        on the billboard. The largest change is 54 spots, with the song Act II:
        Date @ 8. All the big changes are in the green, due to a large fall not
        physically being able to be shown on the billboard anymore.
    </p>
</div>
{% endblock %}

billboard/rankings/templates/rankings/favorites.html
{% extends "base.html" %}

{% block content %}
    <h2>My Favorite Songs</h2>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Song</th>
                <th>Artist</th>
                <th>Actions</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for favorite in object_list %}
                <tr>
                    <td>{{ favorite.added_date }}
                    <td>{{ favorite.song.title }}</td>
                    <td>{{ favorite.song.artist }}</td>
                    <td>
                        <a href="{% url 'rankings:song_detail' favorite.song.id %}">View</a>
                    </td>
                    <td>
                        <form method="post" action="{% url 'rankings:toggle_favorites' favorite.song.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="redirect_to_favorites" value="true">
                            <button type="submit">Remove from Favorites</button>
                        </form>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    No favorite songs found.
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

billboard/rankings/templates/rankings/search.html
{% extends "base.html" %}

{% block content %}
<h1>Search for a Song</h1>
<form method="get" action="{% url 'rankings:search' %}">
    <input type="text" name="q" value="{{ query }}" placeholder="Search for a song">
    <button type="submit">Search</button>
</form>

{% if songs %}
    <ul>
        {% for song in songs %}
        <li><a href="{% url 'rankings:song_detail' song.id %}"><b>{{ song.title }}</b></a> by {{ song.artist }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No songs found.</p>
{% endif %}
{% endblock %}

billboard/rankings/templates/rankings/song_detail.html
{% extends "base.html" %}

{% load django_vite %}

{% block content %}
<div id="app">
    <app></app>
</div>
<img src="data:image/png;base64,{{ chart_image }}" alt="Chart History">
{% endblock content %}

{% block js %}
    {{ block.super }}
    <script>
        var ext_csrf_token = '{{ csrf_token }}';
        var ext_songData = {{ song_dict | safe }};
    </script>
    {% vite_hmr_client %}
    {% vite_asset 'src/apps/song_show/song_show.js' %}
{% endblock js %}

billboard/rankings/templates/rankings/song_list.html
{% extends "base.html" %}

{% block content %}
<h2>Song List</h2>

<form method="get" action="{% url 'rankings:update_songs' %}">
    <label for="date">Select a date:</label>
    <input type="date" id="date" name="date" value="{{ request.GET.date|default_if_none:'' }}" required>
    <button type="submit" name="action" value="filter">Filter</button>
    {% if not songs %}
        <button type="submit" name="action" value="fetch">Get Data</button>
    {% endif %}
</form>

<table>
    <thead>
        <tr>
            <th>Rank</th>
            <th>Peak</th>
            <th>Title</th>
            <th>Artist</th>
        </tr>
    </thead>
    <tbody>
        {% for song in songs %}
        <tr>
            <td><b>{{ song.rank }}</b></td>
            <td>{{ song.peak_position }}</td>
            <td><a href="{% url 'rankings:song_detail' song.id %}">{{ song.title }}</a></td>
            <td>{{ song.artist }}</td>
        </tr>
        {% empty %}
        <tr>
            No song data found.
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}